const requirement = alert("je moet 3 vragen beantwoorden")
var name = prompt("wat is je naampje", "")
var surname = prompt("wat is je acher naam", "")
var age = prompt("wat is je leeftijd", "")
document.write("Hallo chinees wtf voor naam is ")
document.write(name + " " + surname + " nou weer")
document.write("<br/>")
document.write("jij bent " + age + " zo zo grote jongen")
document.write("<br/>")
document.write("<br/>")